# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 865)

        self.MainWindow = MainWindow
        MainWindow.setWindowFlags(QtCore.Qt.CustomizeWindowHint)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        MainWindow.setMouseTracking(True)
        MainWindow._startPos = None
        MainWindow.mousePressEvent = self.mousePressEvent
        MainWindow.mouseMoveEvent = self.mouseMoveEvent
        MainWindow.mouseReleaseEvent = self.mouseReleaseEvent

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_back = QtWidgets.QLabel(self.centralwidget)
        self.label_back.setGeometry(QtCore.QRect(10, 0, 1081, 841))
        self.label_back.setStyleSheet("border-radius:30px;\n"
                                      "background-color: rgb(188, 234, 255);")
        self.label_back.setText("")
        self.label_back.setObjectName("label_back")

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1101, 841))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 110, 871, 741))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 911, 181))
        self.widget_2.setObjectName("widget_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 0, 861, 181))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 71, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icons/student.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser.setGeometry(QtCore.QRect(130, 50, 71, 31))
        self.textBrowser.setStyleSheet("border：none；")
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.groupBox_9)
        self.label_5.setGeometry(QtCore.QRect(130, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_9)
        self.label_6.setGeometry(QtCore.QRect(260, 20, 71, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("icons/学位帽_degree-hat.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setGeometry(QtCore.QRect(360, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_2.setGeometry(QtCore.QRect(360, 50, 71, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 120, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 120, 321, 31))
        self.comboBox_5.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.comboBox_5.setObjectName("comboBox_5")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setGeometry(QtCore.QRect(0, 190, 861, 571))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 571))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 1800))

        self.scrollAreaWidgetContents.setStyleSheet("background-color: %s;" % QColor(188, 234, 255).name())

        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 810, 500))
        self.groupBox.setStyleSheet("QGroupBox { background-color: %s; }" % QColor(188, 234, 255).name())
        self.groupBox.setObjectName("groupBox")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(50, 30, 700, 450))
        self.label_27.setStyleSheet("image: url(:/icons1/icons1/人像卡片上_people-top-card.png);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 520, 810, 500))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(50, 30, 700, 450))
        self.label_30.setStyleSheet("image: url(:/icons1/icons1/人像卡片上_people-top-card.png);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 1040, 810, 500))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setGeometry(QtCore.QRect(50, 30, 700, 450))
        self.label_45.setStyleSheet("image: url(:/icons1/icons1/人像卡片上_people-top-card.png);")
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 0, 851, 721))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setStyleSheet("background-color: rgb(188, 234, 255);")
        self.groupBox_10.setObjectName("groupBox_10")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 801, 621))
        self.tableWidget.setStyleSheet("background-color: rgb(188, 234, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_10)
        self.widget_4.setGeometry(QtCore.QRect(10, 10, 821, 61))
        self.widget_4.setObjectName("widget_4")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(40, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_6.setGeometry(QtCore.QRect(170, 20, 321, 31))
        self.comboBox_6.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.comboBox_6.setObjectName("comboBox_6")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_15.setGeometry(QtCore.QRect(540, 20, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("#pushButton_15{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.widget_6 = QtWidgets.QWidget(self.page_3)
        self.widget_6.setGeometry(QtCore.QRect(-10, 0, 911, 771))
        self.widget_6.setObjectName("widget_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 861, 571))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(140, 90, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(210, 80, 321, 31))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(140, 170, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 170, 321, 31))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(140, 270, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 260, 321, 31))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(120, 370, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 360, 321, 31))
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_teacher = QtWidgets.QLabel(self.widget_6)
        self.label_teacher.setGeometry(QtCore.QRect(600, 250, 200, 200))
        self.label_teacher.setText("")
        self.label_teacher.setPixmap(QtGui.QPixmap("icons/teacher.png"))
        self.label_teacher.setScaledContents(True)
        self.label_teacher.setObjectName("label_teacher")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(320, 460, 121, 28))
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_16 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 0, 861, 81))
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.label_9 = QtWidgets.QLabel(self.groupBox_16)
        self.label_9.setGeometry(QtCore.QRect(300, 30, 200, 32))
        self.label_9.setStyleSheet("#label_9{\n"
                                   "    font:30px;\n"
                                   "    font-weight:bold;\n"
                                   "}")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.widget_8 = QtWidgets.QWidget(self.page_4)
        self.widget_8.setGeometry(QtCore.QRect(0, 0, 911, 771))
        self.widget_8.setObjectName("widget_8")
        self.label_15 = QtWidgets.QLabel(self.widget_8)
        self.label_15.setGeometry(QtCore.QRect(430, 270, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_9.setGeometry(QtCore.QRect(550, 320, 61, 51))
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
                                        "    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"}")
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/内部传输_internal-transmission.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_16 = QtWidgets.QLabel(self.widget_8)
        self.label_16.setGeometry(QtCore.QRect(160, 80, 201, 211))
        self.label_16.setText("")
        self.label_16.setStyleSheet("background-image: url('icons/人像卡片上_people-top-card.png');")
        # self.label_16.setPixmap(QtGui.QPixmap("icons/人像卡片上_people-top-card.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_10.setGeometry(QtCore.QRect(140, 390, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("#pushButton_10{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.comboBox = QtWidgets.QComboBox(self.widget_8)
        self.comboBox.setGeometry(QtCore.QRect(140, 300, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"font: 9pt \"Agency FB\";")
        self.comboBox.setObjectName("comboBox")
        self.label_17 = QtWidgets.QLabel(self.widget_8)
        self.label_17.setGeometry(QtCore.QRect(30, 310, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_8)
        self.label_18.setGeometry(QtCore.QRect(30, 400, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 90, 861, 521))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_15 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 0, 851, 80))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox_15)
        self.label_14.setGeometry(QtCore.QRect(300, 30, 200, 32))
        self.label_14.setStyleSheet("#label_14{\n"
                                   "    font:30px;\n"
                                   "    font-weight:bold;\n"
                                   "}")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.groupBox_7.raise_()
        self.label_15.raise_()
        self.pushButton_9.raise_()
        self.label_16.raise_()
        self.pushButton_10.raise_()
        self.comboBox.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.groupBox_15.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.widget_10 = QtWidgets.QWidget(self.page_5)
        self.widget_10.setGeometry(QtCore.QRect(-10, -10, 921, 791))
        self.widget_10.setObjectName("widget_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.widget_10)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 100, 861, 441))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_20 = QtWidgets.QLabel(self.groupBox_11)
        self.label_20.setGeometry(QtCore.QRect(60, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 60, 221, 31))
        self.lineEdit_5.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 150, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.comboBox_2.setPlaceholderText("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_21 = QtWidgets.QLabel(self.groupBox_11)
        self.label_21.setGeometry(QtCore.QRect(70, 150, 72, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_11)
        self.label_22.setGeometry(QtCore.QRect(40, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 240, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.comboBox_3.setPlaceholderText("")
        self.comboBox_3.setObjectName("comboBox_3")

        self.label_monitor = QtWidgets.QLabel(self.widget_10)
        self.label_monitor.setGeometry(QtCore.QRect(600, 250, 200, 200))
        self.label_monitor.setText("")
        self.label_monitor.setPixmap(QtGui.QPixmap("icons/监控摄像头_monitor-camera.png"))
        self.label_monitor.setScaledContents(True)
        self.label_monitor.setObjectName("label_monitor")

        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_12.setGeometry(QtCore.QRect(190, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("#pushButton_12{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.groupBox_14 = QtWidgets.QGroupBox(self.widget_10)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 861, 81))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_19 = QtWidgets.QLabel(self.groupBox_14)
        self.label_19.setGeometry(QtCore.QRect(320, 30, 200, 32))
        self.label_19.setStyleSheet("#label_19{\n"
                                   "    font:30px;\n"
                                   "    font-weight:bold;\n"
                                   "}")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.widget_11 = QtWidgets.QWidget(self.page_6)
        self.widget_11.setGeometry(QtCore.QRect(0, 0, 911, 81))
        self.widget_11.setObjectName("widget_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.widget_11)
        self.groupBox_12.setGeometry(QtCore.QRect(0, 0, 851, 80))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setGeometry(QtCore.QRect(300, 30, 200, 32))
        self.label_23.setStyleSheet("#label_23{\n"
                                   "    font:30px;\n"
                                   "    font-weight:bold;\n"
                                   "}")
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.widget_12 = QtWidgets.QWidget(self.page_6)
        self.widget_12.setGeometry(QtCore.QRect(0, 90, 911, 681))
        self.widget_12.setObjectName("widget_12")
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget_12)
        self.groupBox_13.setGeometry(QtCore.QRect(0, 0, 851, 631))
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_24 = QtWidgets.QLabel(self.groupBox_13)
        self.label_24.setGeometry(QtCore.QRect(90, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 80, 321, 31))
        self.lineEdit_6.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_25 = QtWidgets.QLabel(self.groupBox_13)
        self.label_25.setGeometry(QtCore.QRect(90, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 190, 321, 31))
        self.comboBox_4.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.comboBox_4.setObjectName("comboBox_4")

        self.label_26 = QtWidgets.QLabel(self.groupBox_13)
        self.label_26.setGeometry(QtCore.QRect(90, 260, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 320, 321, 31))
        self.lineEdit_7.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.label_class = QtWidgets.QLabel(self.widget_12)
        self.label_class.setGeometry(QtCore.QRect(600, 150, 200, 200))
        self.label_class.setText("")
        self.label_class.setPixmap(QtGui.QPixmap("icons/class.png"))
        self.label_class.setScaledContents(True)
        self.label_class.setObjectName("label_class")

        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_14.setGeometry(QtCore.QRect(190, 480, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("#pushButton_14{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.stackedWidget.addWidget(self.page_6)

        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.widget_change_monitor = QtWidgets.QWidget(self.page_7)
        self.widget_change_monitor.setGeometry(QtCore.QRect(-10, -10, 921, 791))
        self.widget_change_monitor.setObjectName("widget_change_monitor")
        self.groupBox_monitor = QtWidgets.QGroupBox(self.widget_change_monitor)
        self.groupBox_monitor.setGeometry(QtCore.QRect(10, 100, 861, 441))
        self.groupBox_monitor.setTitle("")
        self.groupBox_monitor.setObjectName("groupBox_monitor")
        self.label_mo = QtWidgets.QLabel(self.groupBox_monitor)
        self.label_mo.setGeometry(QtCore.QRect(60, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_mo.setFont(font)
        self.label_mo.setObjectName("label_mo")

        self.comboBox_mo = QtWidgets.QComboBox(self.groupBox_monitor)
        self.comboBox_mo.setGeometry(QtCore.QRect(200, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_mo.setFont(font)
        self.comboBox_mo.setStyleSheet("border:2px solid rgb(0,0,0)")
        self.comboBox_mo.setPlaceholderText("")
        self.comboBox_mo.setObjectName("comboBox_mo")

        self.button_show_mo = QtWidgets.QPushButton(self.page_7)
        self.button_show_mo.setGeometry(QtCore.QRect(35, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_show_mo.setFont(font)
        self.button_show_mo.setStyleSheet("#button_show_mo{\n"
                                         "    \n"
                                         "    \n"
                                         "    background-color: rgb(168, 214, 255);\n"
                                         "    border-radius:6px;\n"
                                         "    border:1px solid rgb(0,0,0);\n"
                                         "    font:20px;\n"
                                         "    font-weight: bold;\n"
                                         "}")
        self.button_show_mo.setObjectName("button_show_mo")

        self.button_close_mo = QtWidgets.QPushButton(self.page_7)
        self.button_close_mo.setGeometry(QtCore.QRect(250, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_close_mo.setFont(font)
        self.button_close_mo.setStyleSheet("#button_close_mo{\n"
                                          "    \n"
                                          "    \n"
                                          "    background-color: rgb(168, 214, 255);\n"
                                          "    border-radius:6px;\n"
                                          "    border:1px solid rgb(0,0,0);\n"
                                          "    font:20px;\n"
                                          "    font-weight: bold;\n"
                                          "}")
        self.button_close_mo.setObjectName("button_close_mo")

        self.label_monitor_2 = QtWidgets.QLabel(self.widget_change_monitor)
        self.label_monitor_2.setGeometry(QtCore.QRect(600, 150, 200, 200))
        self.label_monitor_2.setText("")
        self.label_monitor_2.setPixmap(QtGui.QPixmap("icons/监控摄像头_monitor-camera.png"))
        self.label_monitor_2.setScaledContents(True)
        self.label_monitor_2.setObjectName("label_monitor_2")

        self.stackedWidget.addWidget(self.page_7)

        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 10, 861, 91))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")

        self.pushButton_exit = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_exit.setGeometry(QtCore.QRect(800, 10, 41, 41))
        self.pushButton_exit.setStyleSheet("#pushButton_exit{\n"
                                           "    image: url(icons/关闭_close-one.png);\n"
                                           "    border:none;\n"
                                           "}")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.pushButton_min = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_min.setGeometry(QtCore.QRect(750, 10, 41, 41))
        self.pushButton_min.setStyleSheet("#pushButton_min{\n"
                                        "    border:none;\n"
                                        "}")
        self.pushButton_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon)
        self.pushButton_min.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_min.setObjectName("pushButton_min")

        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(790, 50, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(630, 0, 100, 100))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("icons/人员_people.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 110, 191, 741))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")

        self.pushButton_mo = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_mo.setGeometry(QtCore.QRect(10, 370, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mo.setFont(font)
        self.pushButton_mo.setStyleSheet("#pushButton_mo{\n"
                                        "    \n"
                                        "    \n"
                                        "    background-color: rgb(168, 214, 255);\n"
                                        "    border-radius:6px;\n"
                                        "    border:1px solid rgb(0,0,0);\n"
                                        "    font:20px;\n"
                                        "    font-weight: bold;\n"
                                        "}")
        self.pushButton_mo.setObjectName("pushButton_mo")

        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 270, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 220, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 170, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"\n"
"    \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 320, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("#pushButton_16{\n"
"    \n"
"    \n"
"    background-color: rgb(168, 214, 255);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(0,0,0);\n"
"    font:20px;\n"
"    font-weight: bold;\n"
"\n"
"    \n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 10, 191, 91))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setGeometry(QtCore.QRect(40, 0, 100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/电脑_computer.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        self.pushButton_min.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self._startPos = event.pos()


    def mouseMoveEvent(self, event):
        if self._startPos:
            delta = event.pos() - self._startPos
            # self.move(self.pos() + delta)
            self.MainWindow.move(self.MainWindow.pos() + delta)


    def mouseReleaseEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self._startPos = None

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "学生总数"))
        self.label_7.setText(_translate("MainWindow", "班级总数"))
        self.pushButton_7.setText(_translate("MainWindow", "切换班级"))
        self.groupBox.setTitle(_translate("MainWindow", "班级概况"))
        self.groupBox_2.setTitle(_translate("MainWindow", "优秀学生"))
        self.groupBox_5.setTitle(_translate("MainWindow", "各平均时长占比"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "学生姓名"))
        self.tableWidget.setStyleSheet("#item{ background-color: %s; }" % QColor(0, 0, 0).name())
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "学生ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "总时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "抬头时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "低头时间"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "趴下时间"))
        self.label_8.setText(_translate("MainWindow", "学生列表"))
        self.pushButton_15.setText(_translate("MainWindow", "切换班级"))
        self.label_10.setText(_translate("MainWindow", "姓名"))
        self.label_11.setText(_translate("MainWindow", "学校"))
        self.label_12.setText(_translate("MainWindow", "性别"))
        self.label_13.setText(_translate("MainWindow", "职工号"))
        self.pushButton_8.setText(_translate("MainWindow", "保存"))
        self.label_9.setText(_translate("MainWindow", "教师信息录入"))
        self.label_15.setText(_translate("MainWindow", "从Excel表导入学生基本信息"))
        self.pushButton_10.setText(_translate("MainWindow", "点击添加"))
        self.label_17.setText(_translate("MainWindow", "选择学生"))
        self.label_18.setText(_translate("MainWindow", "选择照片"))
        self.label_14.setText(_translate("MainWindow", "学生信息导入"))
        self.label_20.setText(_translate("MainWindow", "职工号："))
        self.label_mo.setText(_translate("MainWindow", "监控号："))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "请输入"))
        self.label_21.setText(_translate("MainWindow", "班级："))
        self.label_22.setText(_translate("MainWindow", "监控编码："))
        self.pushButton_12.setText(_translate("MainWindow", "保存"))
        self.label_19.setText(_translate("MainWindow", "绑定监控"))
        self.label_23.setText(_translate("MainWindow", "创建班级信息"))
        self.label_24.setText(_translate("MainWindow", "教师ID："))
        self.label_25.setText(_translate("MainWindow", "年级："))
        self.label_26.setText(_translate("MainWindow", "班级号（请填写数字）："))
        self.pushButton_14.setText(_translate("MainWindow", "保存"))
        self.button_show_mo.setText(_translate("MainWindow", "显示监控"))
        self.button_close_mo.setText(_translate("MainWindow", "关闭监控"))
        self.label_2.setText(_translate("MainWindow", "教室智能监控与分析系统"))
        self.label_3.setText(_translate("MainWindow", "欢迎！"))
        self.pushButton_mo.setText(_translate("MainWindow", "显示监控"))
        self.pushButton_6.setText(_translate("MainWindow", "创建班级"))
        self.pushButton_5.setText(_translate("MainWindow", "绑定监控"))
        self.pushButton_4.setText(_translate("MainWindow", "学生导入"))
        self.pushButton_3.setText(_translate("MainWindow", "信息录入"))
        self.pushButton_2.setText(_translate("MainWindow", "学生列表"))
        self.pushButton.setText(_translate("MainWindow", "班级概况"))
        self.pushButton_16.setText(_translate("MainWindow", "刷新"))
import resource_rc
