# Generated by Django 3.2.13 on 2022-06-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_account',
            fields=[
                ('tid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='教师编号')),
                ('taccount', models.CharField(max_length=50, verbose_name='教师用户名')),
                ('tpassword', models.CharField(max_length=50, verbose_name='教师密码')),
            ],
            options={
                'db_table': 'teacher_account',
            },
        ),
        migrations.CreateModel(
            name='teacher_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('tsex', models.BooleanField(default=True, verbose_name='教师性别')),
                ('tschool', models.CharField(max_length=50, verbose_name='教师学校')),
                ('tid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.teacher_account')),
            ],
            options={
                'db_table': 'teacher_infomation',
            },
        ),
    ]
