# Generated by Django 3.2.13 on 2022-06-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20220625_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_info',
            old_name='ccnumber',
            new_name='cnumber',
        ),
    ]
