# Generated by Django 3.2.13 on 2022-06-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_rename_ccnumber_class_info_cnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='spic',
            field=models.ImageField(max_length=50, upload_to='', verbose_name='学生照片'),
        ),
    ]
