# Generated by Django 3.2.13 on 2022-06-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_student_info_spic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='spic',
            field=models.CharField(max_length=50, verbose_name='学生照片'),
        ),
    ]
