# Generated by Django 3.2.13 on 2022-07-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_student_info_spic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='spic',
            field=models.CharField(max_length=100, verbose_name='学生照片'),
        ),
    ]
