# Generated by Django 3.2.13 on 2022-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_student_info_spic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLCCTV',
            fields=[
                ('cctv', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='cctv')),
            ],
            options={
                'db_table': 'all_cctv',
            },
        ),
    ]
