# Generated by Django 3.2.13 on 2022-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_class_info_cctv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_info',
            name='cctv',
            field=models.CharField(max_length=50, null=True, verbose_name='监控编号'),
        ),
    ]
