# Generated by Django 3.2.13 on 2022-07-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_class_info_cctv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_info',
            name='cctv',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.allcctv'),
        ),
    ]
