# Generated by Django 3.2.13 on 2022-07-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_class_info_cctv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_info',
            old_name='cctv',
            new_name='cctv_id',
        ),
    ]
