# Generated by Django 3.2.13 on 2022-07-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_rename_cctv_class_info_cctv_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_info',
            old_name='cctv_id',
            new_name='cctv',
        ),
    ]
