# Generated by Django 3.2.13 on 2022-07-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_rename_cctv_id_class_info_cctv'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcctv',
            name='update_num',
            field=models.IntegerField(null=True, verbose_name='update_num'),
        ),
    ]
